version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python src/main.py
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - backend/env/local.txt
    environment:
      - LOG_CONF=env/logging.json

